#THIS IS THE PLACE FOR YOUR API KEYS SO THAT YOU WON'T BE HARDCODING IT [...]
#[...] INTO YOUR SCRIPT, USE THAT FILE CAREFULLY AND DO NOT SHOW THIS FILE PUBLICLY

export GITHUB_TOKEN=""
export GITHUB_TOKEN2=""
